# Generated by Django 3.0.5 on 2021-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210220_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('django_admin', 'Django Admin')], default='user'),
        ),
    ]
