# Generated by Django 3.0.5 on 2021-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.IntegerField(default=1, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('text', 'score'), name='unique_author'),
        ),
    ]
