# Generated by Django 3.0.5 on 2021-02-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_review_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author',
        ),
    ]
