# Generated by Django 3.0.5 on 2021-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210218_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
